In [2]:
import pandas as pd
df1 = pd.read_csv('review1.csv')
df1=df1.drop(['text','review_id','funny','cool'], axis=1)

In [3]:
df2 = pd.read_csv('review2.csv')
df2=df2.drop(['text','review_id','funny','cool'], axis=1)

In [4]:
df3 = pd.read_csv('review3.csv')
df3=df3.drop(['text','review_id','funny','cool'], axis=1)

In [5]:
df4 = pd.read_csv('review4.csv')
df4=df4.drop(['text','review_id','funny','cool'], axis=1)

In [6]:
df5 = pd.read_csv('review5.csv')
df5=df5.drop(['text','review_id','funny','cool'], axis=1)

In [7]:
df6 = pd.read_csv('review6.csv')
df6=df6.drop(['text','review_id','funny','cool'], axis=1)

In [8]:
df7 = pd.read_csv('review7.csv')
df7=df7.drop(['text','review_id','funny','cool'], axis=1)

In [9]:
df8 = pd.read_csv('review8.csv')
df8=df8.drop(['text','review_id','funny','cool'], axis=1)

In [10]:
df9 = pd.read_csv('review9.csv')
df9=df9.drop(['text','review_id','funny','cool'], axis=1)

In [11]:
df10 = pd.read_csv('review10.csv')
df10=df10.drop(['text','review_id','funny','cool'], axis=1)

In [12]:
df11 = pd.read_csv('review11.csv')
df11=df11.drop(['text','review_id','funny','cool'], axis=1)

In [13]:
df12 = pd.read_csv('review12.csv')
df12=df12.drop(['text','review_id','funny','cool'], axis=1)

In [14]:
df13 = pd.read_csv('review13.csv')
df13=df13.drop(['text','review_id','funny','cool'], axis=1)

In [15]:
df14 = pd.read_csv('review14.csv')
df14=df14.drop(['text','review_id','funny','cool'], axis=1)

In [16]:
df15 = pd.read_csv('review15.csv')
df15=df15.drop(['text','review_id','funny','cool'], axis=1)

In [17]:
df16 = pd.read_csv('review16.csv')
df16=df16.drop(['text','review_id','funny','cool'], axis=1)

In [18]:
df17 = pd.read_csv('review17.csv')
df17=df17.drop(['text','review_id','funny','cool'], axis=1)

In [19]:
df18 = pd.read_csv('review18.csv')
df18=df18.drop(['text','review_id','funny','cool'], axis=1)

In [20]:
frames = [df1, df2, df3,df4, df5, df6,df7, df8, df9,df10, df11, df12,df13, df14, df15,df16, df17, df18]
result = pd.concat(frames)

In [21]:
df_b = pd.read_json('yelp_academic_dataset_business.json', lines=True)

In [55]:
df_b=df_b[df_b['city']=='Portland']
df_b.dropna( axis=0, how="any", thresh=None, subset=None, inplace=True)
df_b

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ..."
2,bvN78flM8NLprQ1a1y5dRg,The Reclaimory,4720 Hawthorne Ave,Portland,OR,97214,45.511907,-122.613693,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Antiques, Fashion, Used, Vintage & Consignment...","{'Thursday': '11:0-18:0', 'Friday': '11:0-18:0..."
20,DLbEQySMW3X7KvkybpEYkw,Jasmine Nail Spa,"4370 SE King Rd, Ste 125",Portland,OR,97222,45.447598,-122.617427,3.0,7,0,"{'RestaurantsPriceRange2': '1', 'ByAppointment...","Nail Salons, Beauty & Spas","{'Monday': '9:30-18:0', 'Tuesday': '9:30-18:0'..."
23,j68RDnvOaYEwGcY9cTEHpA,Pittock Mansion,3229 NW Pittock Dr,Portland,OR,97210,45.525259,-122.716227,4.5,406,1,"{'BusinessAcceptsCreditCards': 'True', 'GoodFo...","Tours, Museums, Architectural Tours, Venues & ...","{'Monday': '0:0-0:0', 'Thursday': '10:0-16:0',..."
32,uMGsjQGT35rX4AAt1Hp9og,Laurelhurst Chiropractic,"2705 E Burnside St, Ste 213",Portland,OR,97214,45.523103,-122.638005,4.5,25,1,"{'AcceptsInsurance': 'True', 'ByAppointmentOnl...","Acupuncture, Prenatal/Perinatal Care, Health &...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-18:0', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160521,68nXXzFyK8tzcBlv8eM3tw,McMenamins Barley Mill Pub,1629 S.E. Hawthorne Blvd.,Portland,OR,97214,45.512422,-122.648782,3.5,108,1,"{'HasTV': 'True', 'NoiseLevel': 'u'average'', ...","Pubs, Breweries, Food, American (Traditional),...","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
160526,Xnczteyo1nfsZXvRnx9zqg,Bashor's Team Athletics,4812 N Interstate Ave,Portland,OR,97217,45.557766,-122.681779,3.5,7,1,"{'BusinessParking': '{'garage': False, 'street...","Shopping, Building Supplies, Home Services, Sp...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-15:0', '..."
160530,23URUiNssvknBern9BCbRw,St Johns Auto Center,6514 N Lombard St,Portland,OR,97203,45.585576,-122.733644,4.5,21,1,"{'BusinessAcceptsCreditCards': 'True', 'WiFi':...","Automotive, Body Shops, Auto Repair","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
160537,ER_VMRSD-9FSbw4SGGNQvA,Seaplane,2266 NW Lovejoy St,Portland,OR,97210,45.529592,-122.697685,3.5,13,0,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Fashion, Men's Clothing, Restaurants, Shopping...","{'Monday': '11:0-18:0', 'Tuesday': '11:0-18:0'..."
160561,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21..."

In [56]:
df_new=df_b[df_b.categories.str.contains("Restaurants", na=False)==True]
df_new

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ..."
36,jx91IMdGOmLOo8h_F9z39g,Cleary's Restaurant & Spirits,12429 NE Glisan St,Portland,OR,97230,45.526473,-122.535323,3.5,19,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Nightlife, Sandwiches, Seafood, Restaurants","{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ..."
50,5PsApTz-WqhF_-8mfqGtGw,Cafe Yumm!,301 SW Morrison St,Portland,OR,97204,45.518450,-122.675723,3.5,158,1,"{'OutdoorSeating': 'True', 'GoodForKids': 'Tru...","Vegetarian, Vegan, Sandwiches, Soup, American ...","{'Monday': '10:0-17:0', 'Tuesday': '10:0-17:0'..."
93,HMXiuCxHDXqMH1hBpaHd9g,Whole Time Chicken,,Portland,OR,97215,45.516241,-122.597527,5.0,7,0,"{'OutdoorSeating': 'True', 'RestaurantsTableSe...","Food Stands, Restaurants, Sandwiches","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'..."
94,ZA3u0Nu5V6TqkcYh8U0zdg,B Street Coffee House,2190 W Burnside St,Portland,OR,97210,45.523074,-122.696206,4.5,131,0,"{'Caters': 'False', 'RestaurantsAttire': 'u'ca...","Restaurants, Food, Sandwiches, Breakfast & Bru...","{'Monday': '6:30-15:0', 'Tuesday': '6:30-15:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160509,ny28j9D88xot0Eq54ojpVQ,Fratelli,1230 Nw Hoyt St,Portland,OR,97209,45.527150,-122.683865,3.5,131,0,"{'RestaurantsReservations': 'True', 'BusinessA...","Italian, Restaurants","{'Wednesday': '17:0-22:0', 'Thursday': '17:0-2..."
160512,7r311z2Uq_UzHqu5hiipxA,Thai Garden,SE 102nd And Stark,Portland,OR,97233,45.519297,-122.558636,4.0,165,1,"{'RestaurantsAttire': 'u'casual'', 'Restaurant...","Food Stands, Food, Street Vendors, Restaurants...","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'..."
160521,68nXXzFyK8tzcBlv8eM3tw,McMenamins Barley Mill Pub,1629 S.E. Hawthorne Blvd.,Portland,OR,97214,45.512422,-122.648782,3.5,108,1,"{'HasTV': 'True', 'NoiseLevel': 'u'average'', ...","Pubs, Breweries, Food, American (Traditional),...","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'..."
160537,ER_VMRSD-9FSbw4SGGNQvA,Seaplane,2266 NW Lovejoy St,Portland,OR,97210,45.529592,-122.697685,3.5,13,0,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Fashion, Men's Clothing, Restaurants, Shopping...","{'Monday': '11:0-18:0', 'Tuesday': '11:0-18:0'..."
160561,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21..."

In [46]:
res=result.rename(columns={'stars': 'rates'})
res

,user_id,business_id,rates,useful,date
0,ak0TdVmGKo4pwqdJSTLwWw,buF9druCkbuXLX526sGELQ,4,3,2014-10-11 03:34:02
1,YoVfDbnISlW0f7abNQACIg,RA4V8pr014UyUbDvI-LW2A,4,1,2015-07-03 20:38:25
2,eC5evKn1TWDyHCyQAwguUw,_sS2LBIGNT5NQb6PD1Vtjw,5,0,2013-05-28 20:38:06
3,SFQ1jcnGguO0LYWnbbftAA,0AzLzHfOJgL7ROwhdww2ew,2,1,2010-01-08 02:29:15
4,0kA0PAJ8QFMeveQWHFqz2A,8zehGz9jnxPqXtOc7KaJxA,4,0,2011-07-28 18:05:01
...,...,...,...,...,...
135398,6olZ0y9oW9azON61AhwxYg,yyTtwwQ4JnQMJ2rn3W0S0g,1,0,2021-01-26 04:07:14
135399,EPYNZQFuSKqLi-on3U9dFg,RDgwjgbu5xziFIAaNn3WCQ,1,13,2019-05-01 21:21:43
135400,tr13Jb83h2itjyXVwaO5eA,rbuj2X4SXIc3MDul4dcxIA,5,39,2020-06-13 02:39:26
135401,HqdmRMpNvScFxjGAB40vgQ,IRzjEZ2pX4iOpnBG7oZJ7g,2,2,2020-06-22 21:54:10
135402,HsT8bz3-SKMk7YidwLLM6Q,pxwYIa1jZzHJ4R0Sp1cHFw,5,11,2019-04-17 04:27:39

In [29]:
util=result[result['useful']>=5]
util

,user_id,business_id,stars,useful,date
16,bUHweiErUJ36WGeNrPmEbA,6Hm2FmfLcU_M91TrZI5htA,5,5,2014-02-05 21:09:05
19,jySmPCkEkJR3cWJlkEs9cw,ZW7aI5FO_3q_vSzI4_zx-Q,5,5,2013-08-15 14:47:40
23,d01SZKYmReEar7varZB0HQ,I2OblwJG8_XzFxxoHU0vVQ,4,5,2010-05-14 14:33:54
25,7x863PREK98UuCxYpOszIw,ISBs1ARjIFCXGWqPmGSMog,5,5,2013-05-07 01:49:39
34,s4NgvdIfBH3UQdccWCyARg,IdXHHEUH4ebcxdRxCo3JNw,3,7,2009-10-13 22:20:10
...,...,...,...,...,...
135374,xnf9I953jVkJiqBIIjWJOg,qYANgZTvhdkarq8n1m68bg,4,5,2019-07-02 02:10:16
135375,nRRvAmz3K9jSvenAf_H4wg,CnuJ9rh9xvKJ3EaCo1xIOw,5,6,2020-10-02 16:41:02
135399,EPYNZQFuSKqLi-on3U9dFg,RDgwjgbu5xziFIAaNn3WCQ,1,13,2019-05-01 21:21:43
135400,tr13Jb83h2itjyXVwaO5eA,rbuj2X4SXIc3MDul4dcxIA,5,39,2020-06-13 02:39:26
135402,HsT8bz3-SKMk7YidwLLM6Q,pxwYIa1jZzHJ4R0Sp1cHFw,5,11,2019-04-17 04:27:39

In [47]:
merged=pd.merge(df_new, res)
merged

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,user_id,rates,useful,date
0,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",24gb1QBBEl2xHtVeTzDsCQ,4,1,2012-07-16 05:04:05
1,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",AsDPajAdVBsXydg60AIsdw,5,0,2015-04-28 21:11:10
2,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",Eypq5gLLjCapBVVnMw_MyA,4,0,2015-11-18 18:50:05
3,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",X568BojbbH6cAxqXU5zLwA,5,0,2011-11-30 20:15:41
4,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",gQMsoHpjmzBmBQkkefrLXw,5,2,2016-08-12 23:47:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752035,GB75wPibj3IjNauaoCxyGA,Havana Cafe,910 NW 14th St,Portland,OR,97209,45.529647,-122.685153,4.0,10,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Cuban, Sandwiches, Restaurants, Cafes",None,piw1IjNOORH4yfMuVNoU3A,4,1,2020-09-30 16:15:45
752036,GB75wPibj3IjNauaoCxyGA,Havana Cafe,910 NW 14th St,Portland,OR,97209,45.529647,-122.685153,4.0,10,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Cuban, Sandwiches, Restaurants, Cafes",None,HfF4lqJIw3px1_KZ4-Y3nA,5,1,2020-08-30 00:34:42
752037,GB75wPibj3IjNauaoCxyGA,Havana Cafe,910 NW 14th St,Portland,OR,97209,45.529647,-122.685153,4.0,10,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Cuban, Sandwiches, Restaurants, Cafes",None,OOVvCyoUcYzwEVdh8bnkXQ,5,0,2020-10-03 21:40:33
752038,GB75wPibj3IjNauaoCxyGA,Havana Cafe,910 NW 14th St,Portland,OR,97209,45.529647,-122.685153,4.0,10,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Cuban, Sandwiches, Restaurants, Cafes",None,Z6ay7Ku6uu0anxSsNJUAAw,5,0,2020-08-25 19:19:34
752039,GB75wPibj3IjNauaoCxyGA,Havana Cafe,910 NW 14th St,Portland,OR,97209,45.529647,-122.685153,4.0,10,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Cuban, Sandwiches, Restaurants, Cafes",None,oHqPHNMtQwbA-JVF5gccUg,2,0,2021-01-13 01:22:27

In [49]:
merged=merged[merged['useful']>=4]
merged

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,user_id,rates,useful,date
19,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",Ri1nrLjmtQoDLnULZal3PA,5,7,2010-12-01 07:07:09
20,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",HFECrzYDpgbS5EmTBtj2zQ,4,6,2011-11-05 02:25:19
48,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",DpG3dtVqOsGmKFsNL1MJyA,5,4,2015-06-13 19:24:14
50,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",fG-K5NglgWxHg8PNu62afg,5,9,2011-12-13 00:25:44
58,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",640JloHIU4jEjdVrjlU68A,4,7,2015-06-28 14:04:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751983,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",8lEywHSvti2UjFP8ODbnHg,3,13,2019-03-25 19:05:22
751996,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",6eilRaUDPl1Vz8liYPpZjA,4,6,2020-03-16 06:00:40
752003,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",G1DtOw86TtPYtllePlMAdw,4,4,2018-11-18 23:46:49
752021,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",G1DtOw86TtPYtllePlMAdw,3,5,2018-12-20 23:43:12
752024,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",DEjRvKAJWCrjCaEP-FVJ-g,2,6,2017-12-05 19:32:56

In [58]:
grouped=merged.groupby(by='business_id')
meanrate=grouped['rates'].mean()

In [63]:
#pd.merge(df_new,meanrate)
meanrate=meanrate.to_frame()

AttributeError: 'DataFrame' object has no attribute 'to_frame'

In [65]:
meanrate=meanrate.reset_index()

In [66]:
pd.merge(df_new,meanrate)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,rates
0,tCbdrRPZA0oiIYSmHG3J0w,Flying Elephants at PDX,7000 NE Airport Way,Portland,OR,97218,45.588906,-122.593331,4.0,126,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsAtt...","Salad, Soup, Sandwiches, Delis, Restaurants, C...","{'Monday': '5:0-18:0', 'Tuesday': '5:0-17:0', ...",4.636364
1,jx91IMdGOmLOo8h_F9z39g,Cleary's Restaurant & Spirits,12429 NE Glisan St,Portland,OR,97230,45.526473,-122.535323,3.5,19,1,"{'RestaurantsGoodForGroups': 'True', 'Alcohol'...","Nightlife, Sandwiches, Seafood, Restaurants","{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",2.000000
2,5PsApTz-WqhF_-8mfqGtGw,Cafe Yumm!,301 SW Morrison St,Portland,OR,97204,45.518450,-122.675723,3.5,158,1,"{'OutdoorSeating': 'True', 'GoodForKids': 'Tru...","Vegetarian, Vegan, Sandwiches, Soup, American ...","{'Monday': '10:0-17:0', 'Tuesday': '10:0-17:0'...",2.714286
3,ZA3u0Nu5V6TqkcYh8U0zdg,B Street Coffee House,2190 W Burnside St,Portland,OR,97210,45.523074,-122.696206,4.5,131,0,"{'Caters': 'False', 'RestaurantsAttire': 'u'ca...","Restaurants, Food, Sandwiches, Breakfast & Bru...","{'Monday': '6:30-15:0', 'Tuesday': '6:30-15:0'...",3.000000
4,aTAe3uMYBEwU0FbTMFEI5g,Urban Pantry,1128 NW Lovejoy St,Portland,OR,97209,45.529939,-122.682932,3.5,26,1,"{'HasTV': 'False', 'NoiseLevel': 'u'quiet'', '...","Do-It-Yourself Food, Restaurants, American (Tr...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-19:0', ...",4.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4114,ny28j9D88xot0Eq54ojpVQ,Fratelli,1230 Nw Hoyt St,Portland,OR,97209,45.527150,-122.683865,3.5,131,0,"{'RestaurantsReservations': 'True', 'BusinessA...","Italian, Restaurants","{'Wednesday': '17:0-22:0', 'Thursday': '17:0-2...",3.250000
4115,7r311z2Uq_UzHqu5hiipxA,Thai Garden,SE 102nd And Stark,Portland,OR,97233,45.519297,-122.558636,4.0,165,1,"{'RestaurantsAttire': 'u'casual'', 'Restaurant...","Food Stands, Food, Street Vendors, Restaurants...","{'Monday': '11:0-20:0', 'Tuesday': '11:0-20:0'...",4.500000
4116,68nXXzFyK8tzcBlv8eM3tw,McMenamins Barley Mill Pub,1629 S.E. Hawthorne Blvd.,Portland,OR,97214,45.512422,-122.648782,3.5,108,1,"{'HasTV': 'True', 'NoiseLevel': 'u'average'', ...","Pubs, Breweries, Food, American (Traditional),...","{'Monday': '12:0-20:0', 'Tuesday': '12:0-20:0'...",2.833333
4117,ER_VMRSD-9FSbw4SGGNQvA,Seaplane,2266 NW Lovejoy St,Portland,OR,97210,45.529592,-122.697685,3.5,13,0,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Fashion, Men's Clothing, Restaurants, Shopping...","{'Monday': '11:0-18:0', 'Tuesday': '11:0-18:0'...",4.000000
4118,jYgqSazE0gUyI7qq086Dzw,Chart House,5700 SW Terwilliger,Portland,OR,97239,45.483154,-122.682748,3.5,457,1,"{'BusinessAcceptsCreditCards': 'True', 'Outdoo...","Event Planning & Services, Steakhouses, Seafoo...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21...",2.212121